<h1>Analisís general del dataset MHEALTH</h1>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import glob
import seaborn as sns

In [2]:

import glob
import pandas as pd
import re

# Busca todos los archivos
files = glob.glob(r"../DataSets/MHEALTHDATASET/mHealth_subject*.log")

dfs = []

for file in files:
    
    # Extraer número de sujeto desde el nombre del archivo
    subject_id = int(re.search(r"subject(\d+)", file).group(1))
    
    # Leer archivo
    df = pd.read_csv(file, sep='\t', header=None)
    
    # Agregar columna subject_id
    df["subject_id"] = subject_id
    
    dfs.append(df)

# Unir todos
MHEALTHDATASET = pd.concat(dfs, ignore_index=True)

# Asignar nombres de columnas
MHEALTHDATASET.columns = [  
    # Chest sensor
    "chest_acc_x",
    "chest_acc_y",
    "chest_acc_z",
    "ecg_1",
    "ecg_2",

    # Left ankle
    "ankle_acc_x",
    "ankle_acc_y",
    "ankle_acc_z",
    "ankle_gyro_x",
    "ankle_gyro_y",
    "ankle_gyro_z",
    "ankle_mag_x",
    "ankle_mag_y",
    "ankle_mag_z",

    # Right lower arm
    "arm_acc_x",
    "arm_acc_y",
    "arm_acc_z",
    "arm_gyro_x",
    "arm_gyro_y",
    "arm_gyro_z",
    "arm_mag_x",
    "arm_mag_y",
    "arm_mag_z",

    # Label
    "activity_label",
    
    # Nuevo
    "subject_id"
]

pd.set_option('display.max_columns', None)

<h1>Dimensiones del dataset</h1>

In [3]:
MHEALTHDATASET.shape

(1215745, 25)

<h1>Primeras 5 líneas</h1>

In [4]:
MHEALTHDATASET.head()

,chest_acc_x,chest_acc_y,chest_acc_z,ecg_1,ecg_2,ankle_acc_x,ankle_acc_y,ankle_acc_z,ankle_gyro_x,ankle_gyro_y,ankle_gyro_z,ankle_mag_x,ankle_mag_y,ankle_mag_z,arm_acc_x,arm_acc_y,arm_acc_z,arm_gyro_x,arm_gyro_y,arm_gyro_z,arm_mag_x,arm_mag_y,arm_mag_z,activity_label,subject_id
0,-9.8184,0.009971,0.29563,0.004186,0.004186,2.1849,-9.6967,0.63077,0.103900,-0.84053,-0.68762,-0.370000,-0.36327,0.29963,-8.6499,-4.5781,0.187760,-0.44902,-1.0103,0.034483,-2.35000,-1.610200,-0.030899,0,1
1,-9.8489,0.524040,0.37348,0.004186,0.016745,2.3876,-9.5080,0.68389,0.085343,-0.83865,-0.68369,-0.197990,-0.18151,0.58298,-8.6275,-4.3198,0.023595,-0.44902,-1.0103,0.034483,-2.16320,-0.882540,0.326570,0,1
2,-9.6602,0.181850,0.43742,0.016745,0.037677,2.4086,-9.5674,0.68113,0.085343,-0.83865,-0.68369,-0.374170,0.18723,0.43851,-8.5055,-4.2772,0.275720,-0.44902,-1.0103,0.034483,-1.61750,-0.165620,-0.030693,0,1
3,-9.6507,0.214220,0.24033,0.079540,0.117220,2.1814,-9.4301,0.55031,0.085343,-0.83865,-0.68369,-0.017271,0.18366,0.57571,-8.6279,-4.3163,0.367520,-0.45686,-1.0082,0.025862,-1.07710,0.006945,-0.382620,0,1
4,-9.7030,0.303890,0.31156,0.221870,0.205130,2.4173,-9.3889,0.71098,0.085343,-0.83865,-0.68369,-0.374390,-0.54671,0.44586,-8.7008,-4.1459,0.407290,-0.45686,-1.0082,0.025862,-0.53684,0.175900,-1.095500,0,1

<h1>Datos nulos</h1>

In [5]:
MHEALTHDATASET.isnull().sum()

chest_acc_x       0
chest_acc_y       0
chest_acc_z       0
ecg_1             0
ecg_2             0
ankle_acc_x       0
ankle_acc_y       0
ankle_acc_z       0
ankle_gyro_x      0
ankle_gyro_y      0
ankle_gyro_z      0
ankle_mag_x       0
ankle_mag_y       0
ankle_mag_z       0
arm_acc_x         0
arm_acc_y         0
arm_acc_z         0
arm_gyro_x        0
arm_gyro_y        0
arm_gyro_z        0
arm_mag_x         0
arm_mag_y         0
arm_mag_z         0
activity_label    0
subject_id        0
dtype: int64

<h1>Tipos de datos</h1>

In [6]:
MHEALTHDATASET.dtypes

chest_acc_x       float64
chest_acc_y       float64
chest_acc_z       float64
ecg_1             float64
ecg_2             float64
ankle_acc_x       float64
ankle_acc_y       float64
ankle_acc_z       float64
ankle_gyro_x      float64
ankle_gyro_y      float64
ankle_gyro_z      float64
ankle_mag_x       float64
ankle_mag_y       float64
ankle_mag_z       float64
arm_acc_x         float64
arm_acc_y         float64
arm_acc_z         float64
arm_gyro_x        float64
arm_gyro_y        float64
arm_gyro_z        float64
arm_mag_x         float64
arm_mag_y         float64
arm_mag_z         float64
activity_label      int64
subject_id          int64
dtype: object

<h1>Resumen estadístico</h1>

In [7]:
MHEALTHDATASET.describe().map(lambda x: f"{x:.6f}")

,chest_acc_x,chest_acc_y,chest_acc_z,ecg_1,ecg_2,ankle_acc_x,ankle_acc_y,ankle_acc_z,ankle_gyro_x,ankle_gyro_y,ankle_gyro_z,ankle_mag_x,ankle_mag_y,ankle_mag_z,arm_acc_x,arm_acc_y,arm_acc_z,arm_gyro_x,arm_gyro_y,arm_gyro_z,arm_mag_x,arm_mag_y,arm_mag_z,activity_label,subject_id
count,1215745.000000,1215745.000000,1215745.000000,1215745.000000,1215745.000000,1215745.000000,1215745.000000,1215745.000000,1215745.000000,1215745.000000,1215745.000000,1215745.000000,1215745.000000,1215745.000000,1215745.000000,1215745.000000,1215745.000000,1215745.000000,1215745.000000,1215745.000000,1215745.000000,1215745.000000,1215745.000000,1215745.000000,1215745.000000
mean,-8.522361,-0.214001,-1.055950,-0.005122,-0.004506,1.494200,-9.692878,-0.954806,-0.001599,-0.616632,-0.158781,0.481871,-0.805401,-0.856616,-3.713413,-5.805526,2.393880,-0.276106,-0.466434,0.266633,0.170214,0.714463,-0.366813,1.741465,5.270370
std,4.075293,2.138954,3.574163,0.746597,0.727040,3.826485,4.171303,5.461803,0.491217,0.354641,0.546798,63.957641,42.736417,17.682235,4.763586,5.757639,3.876503,0.527689,0.555551,0.564380,26.676168,33.444532,69.550692,3.283679,2.948526
min,-22.438000,-20.188000,-18.401000,-8.619600,-8.619600,-22.146000,-19.619000,-19.373000,-2.146600,-7.789900,-2.626700,-357.560000,-365.670000,-282.390000,-22.361000,-18.972000,-18.239000,-8.339200,-3.570800,-2.689700,-319.030000,-363.900000,-717.550000,0.000000,1.000000
25%,-9.804000,-1.272900,-2.867300,-0.234430,-0.188380,0.141310,-10.201000,-2.649400,-0.435990,-0.818010,-0.593320,-17.733000,-6.616400,-2.833100,-6.076000,-9.404200,0.129650,-0.705880,-0.897330,-0.237070,-6.191900,-9.519500,-14.238000,0.000000,3.000000
50%,-9.311400,-0.353810,-0.870200,-0.071167,-0.041863,1.308900,-9.670300,-0.016456,-0.014842,-0.707320,-0.190570,0.008828,0.525260,-0.434990,-2.977600,-7.461500,1.928100,-0.354900,-0.634500,0.301720,0.362620,0.352170,-0.672960,0.000000,5.000000
75%,-7.637100,0.709780,0.725910,0.159080,0.150710,2.575800,-9.042200,1.301300,0.448980,-0.540340,0.322200,3.290200,3.500600,1.976900,-1.193700,-2.533900,4.914700,0.096078,-0.106780,0.778020,6.792300,10.076000,13.186000,2.000000,8.000000
max,19.094000,20.927000,26.196000,8.514900,8.519100,20.054000,21.161000,25.015000,60.484000,2.011300,2.770100,339.220000,336.240000,272.560000,19.864000,22.191000,25.741000,3.319600,1.556500,2.750000,251.150000,337.760000,657.180000,12.000000,10.000000

<h1>Distribucion de clases</h1>

In [8]:
MHEALTHDATASET['activity_label'].value_counts()

activity_label
0     872550
1      30720
2      30720
3      30720
4      30720
9      30720
10     30720
11     30720
5      30720
7      29441
8      29337
6      28315
12     10342
Name: count, dtype: int64

<h1>Ruido del dataset</h1>

In [15]:
noise = MHEALTHDATASET[MHEALTHDATASET["activity_label"] == 1]["chest_acc_x"].std()
noise

0.2460398852343575

In [16]:
for act in MHEALTHDATASET["activity_label"].unique():
    std = MHEALTHDATASET[MHEALTHDATASET["activity_label"] == act]["chest_acc_x"].std()
    print(f"Actividad {act} → ruido aprox: {std/noise}")

Actividad 0 → ruido aprox: 12.699549178424467
Actividad 1 → ruido aprox: 1.0
Actividad 2 → ruido aprox: 1.9620213416834977
Actividad 3 → ruido aprox: 6.100305232428157
Actividad 4 → ruido aprox: 8.94368745542987
Actividad 6 → ruido aprox: 19.86867041369008
Actividad 7 → ruido aprox: 1.8807060105467377
Actividad 8 → ruido aprox: 9.056838023537114
Actividad 9 → ruido aprox: 5.578089605980479
Actividad 10 → ruido aprox: 37.766200268527555
Actividad 11 → ruido aprox: 41.32626527866691
Actividad 12 → ruido aprox: 43.70641661364814
Actividad 5 → ruido aprox: 8.264768316789395

<h1>Correlación entre los atributos</h1>

In [9]:
sensores_fisicos = MHEALTHDATASET.drop(columns=['activity_label'])
sensores_fisicos.corr()

,chest_acc_x,chest_acc_y,chest_acc_z,ecg_1,ecg_2,ankle_acc_x,ankle_acc_y,ankle_acc_z,ankle_gyro_x,ankle_gyro_y,ankle_gyro_z,ankle_mag_x,ankle_mag_y,ankle_mag_z,arm_acc_x,arm_acc_y,arm_acc_z,arm_gyro_x,arm_gyro_y,arm_gyro_z,arm_mag_x,arm_mag_y,arm_mag_z,subject_id
chest_acc_x,1.000000,0.075047,0.177665,0.023738,-0.002557,0.049533,0.306326,0.102474,0.042825,0.248209,0.049661,0.091771,0.010943,-0.031728,0.265554,0.192660,0.006852,0.064624,0.129873,0.072662,0.010131,0.012216,0.002987,0.009033
chest_acc_y,0.075047,1.000000,-0.347484,0.026654,0.006867,-0.028290,-0.091808,-0.099557,-0.037858,-0.119972,-0.173718,-0.035794,-0.028994,0.034639,0.060447,-0.045245,-0.027285,0.040271,-0.148965,-0.011235,-0.043702,-0.058541,0.123086,-0.068710
chest_acc_z,0.177665,-0.347484,1.000000,-0.009654,-0.009729,0.089834,0.229559,0.234645,0.048494,0.250113,0.229950,0.107050,0.022669,-0.040221,-0.071137,0.308582,0.003834,-0.063382,0.333775,0.002792,-0.006107,-0.015756,0.029140,-0.044217
ecg_1,0.023738,0.026654,-0.009654,1.000000,0.596522,0.004474,0.002673,0.000312,-0.002104,0.010112,-0.015177,0.011720,-0.003424,0.008074,-0.006348,-0.015570,0.012607,0.013202,-0.024703,-0.001834,0.010237,-0.018949,0.021411,0.006971
ecg_2,-0.002557,0.006867,-0.009729,0.596522,1.000000,-0.002336,-0.005057,0.000327,0.012728,0.005582,-0.012295,0.013318,0.002149,0.000225,-0.010993,-0.028891,0.021917,0.022226,-0.033284,-0.003162,0.009626,-0.005878,0.003344,0.010955
ankle_acc_x,0.049533,-0.028290,0.089834,0.004474,-0.002336,1.000000,0.017623,-0.071447,0.062249,0.086861,-0.034433,-0.030568,-0.223489,0.042373,-0.051124,0.060467,-0.003893,-0.025895,0.063999,0.016274,-0.010497,0.001437,0.004502,0.060195
ankle_acc_y,0.306326,-0.091808,0.229559,0.002673,-0.005057,0.017623,1.000000,0.077962,0.049371,0.350496,0.058061,0.067268,0.033031,-0.026830,0.067072,0.105946,0.092445,0.049759,0.152128,0.105169,-0.049500,-0.060944,0.004695,-0.021288
ankle_acc_z,0.102474,-0.099557,0.234645,0.000312,0.000327,-0.071447,0.077962,1.000000,0.029332,0.164673,0.126219,-0.206537,-0.070765,0.120252,-0.124775,0.192842,0.086563,0.042051,0.076887,-0.004969,0.029342,0.013785,0.017542,0.054048
ankle_gyro_x,0.042825,-0.037858,0.048494,-0.002104,0.012728,0.062249,0.049371,0.029332,1.000000,0.138167,0.111437,-0.034854,-0.026839,0.044039,0.015465,-0.003553,0.058735,0.368314,0.027308,0.591376,0.020086,0.026516,-0.030014,0.163003
ankle_gyro_y,0.248209,-0.119972,0.250113,0.010112,0.005582,0.086861,0.350496,0.164673,0.138167,1.000000,0.005295,0.044589,0.014491,0.023185,-0.079234,0.139140,0.082565,0.106395,0.204324,0.124094,-0.055375,-0.039157,0.065385,0.051813
ankle_gyro_z,0.049661,-0.173718,0.229950,-0.015177,-0.012295,-0.034433,0.058061,0.126219,0.111437,0.005295,1.000000,-0.083859,-0.006219,-0.037827,0.064995,0.034535,0.052691,-0.153966,0.420649,0.345874,0.046614,0.041316,-0.115319,-0.015702
ankle_mag_x,0.091771,-0.035794,0.107050,0.011720,0.013318,-0.030568,0.067268,-0.206537,-0.034854,0.044589,-0.083859,1.000000,0.258480,-0.132887,-0.005729,-0.102934,-0.058124,-0.007084,0.021709,-0.000374,-0.218574,-0.166720,0.348718,0.001011
ankle_mag_y,0.010943,-0.028994,0.022669,-0.003424,0.002149,-0.223489,0.033031,-0.070765,-0.026839,0.014491,-0.006219,0.258480,1.000000,-0.037514,0.011646,-0.021691,-0.016950,-0.006359,0.007399,-0.000977,-0.052490,-0.037201,0.113033,0.000046
ankle_mag_z,-0.031728,0.034639,-0.040221,0.008074,0.000225,0.042373,-0.026830,0.120252,0.044039,0.023185,-0.037827,-0.132887,-0.037514,1.000000,-0.060600,0.026909,0.021326,0.006479,-0.010859,-0.002812,0.012027,0.024670,0.018691,-0.001564
arm_acc_x,0.265554,0.060447,-0.071137,-0.006348,-0.010993,-0.051124,0.067072,-0.124775,0.015465,-0.079234,0.064995,-0.005729,0.011646,-0.060600,1.000000,-0.166167,0.090329,0.378308,-0.221799,0.099683,-0.030644,-0.055584,-0.057070,-0.029141
arm_acc_y,0.192660,-0.045245,0.308582,-0.015570,-0.028891,0.060467,0.105946,0.192842,-0.003553,0.139140,0.034535,-0.102934,-0.021691,0.026909,-0.166167,1.000000,0.145271,-0.189298,0.592062,0.084862,0.029583,0.049210,0.043234,-0.075491
arm_acc_z,0.006852,-0.027285,0.003834,0.012607,0.021917,-0.003893,0.092445,0.086563,0.058735,0.082565,0.052691,-0.058124,-0.016950,0.021326,0.090329,0.145271,1.000000,0.155024,0.104626,0.396981,0.050072,-0.000531,-0.007279,-0.131513
arm_gyro_x,0.064624,0.040271,-0.063382,0.013202,0.022226,-0.025895,0.049759,0.042051,0.368314,0.106395,-0.153966,-0.007084,-0.006359,0.006479,0.378308,-0.189298,0.155024,1.000000,-0.302279,0.100508,0.003380,-0.006745,0.014182,0.126198
arm_gyro_y,0.129873,-0.148965,0.333775,-0.024703,-0.033284,0.063999,0.152128,0.076887,0.027308,0.204324,0.420649,0.021709,0.007399,-0.010859,-0.221799,0.592062,0.104626,-0.302279,1.000000,0.252616,-0.028532,0.010529,-0.016370,-0.081331
arm_gyro_z,0.072662,-0.011235,0.002792,-0.001834,-0.003162,0.016274,0.105169,-0.004969,0.591376,0.124094,0.345874,-0.000374,-0.000977,-0.002812,0.099683,0.084862,0.396981,0.100508,0.252616,1.000000,-0.010486,0.031846,-0.013609,-0.019893
arm_mag_x,0.010131,-0.043702,-0.006107,0.010237,0.009626,-0.010497,-0.049500,0.029342,0.020086,-0.055375,0.046614,-0.218574,-0.052490,0.012027,-0.030644,0.029583,0.050072,0.003380,-0.028532,-0.010486,1.000000,0.166098,-0.059275,-0.001909
arm_mag_y,0.012216,-0.058541,-0.015756,-0.018949,-0.005878,0.001437,-0.060944,0.013785,0.026516,-0.039157,0.041316,-0.166720,-0.037201,0.024670,-0.055584,0.049210,-0.000531,-0.006745,0.010529,0.031846,0.166098,1.000000,-0.245240,-0.000543
arm_mag_z,0.002987,0.123086,0.029140,0.021411,0.003344,0.004502,0.004695,0.017542,-0.030014,0.065385,-0.115319,0.348718,0.113033,0.018691,-0.057070,0.043234,-0.007279,0.014182,-0.016370,-0.013609,-0.059275,-0.245240,1.000000,-0.003475
subject_id,0.009033,-0.068710,-0.044217,0.006971,0.010955,0.060195,-0.021288,0.054048,0.163003,0.051813,-0.015702,0.001011,0.000046,-0.001564,-0.029141,-0.075491,-0.131513,0.126198,-0.081331,-0.019893,-0.001909,-0.000543,-0.003475,1.000000

<h1>Extracción de características</h1>

In [17]:
fs = 50  # frecuencia de muestreo 
window_size = 3 * fs  # 3 segundos

In [18]:
def extract_sensor_features(x, y, z, prefix):
    
    mag = np.sqrt(x**2 + y**2 + z**2)
    
    feats = {}
    
    # mean
    feats[f"{prefix}_mean_x"] = np.mean(x)
    feats[f"{prefix}_mean_y"] = np.mean(y)
    feats[f"{prefix}_mean_z"] = np.mean(z)
    
    # std
    feats[f"{prefix}_std_x"] = np.std(x)
    feats[f"{prefix}_std_y"] = np.std(y)
    feats[f"{prefix}_std_z"] = np.std(z)
    
    # max
    feats[f"{prefix}_max_x"] = np.max(x)
    feats[f"{prefix}_max_y"] = np.max(y)
    feats[f"{prefix}_max_z"] = np.max(z)
    
    # correlaciones
    feats[f"{prefix}_corr_xy"] = np.corrcoef(x, y)[0,1]
    feats[f"{prefix}_corr_xz"] = np.corrcoef(x, z)[0,1]
    feats[f"{prefix}_corr_yz"] = np.corrcoef(y, z)[0,1]
    
    # magnitud
    feats[f"{prefix}_mean_mag"] = np.mean(mag)
    feats[f"{prefix}_std_mag"] = np.std(mag)
    feats[f"{prefix}_auc"] = np.sum(mag)
    feats[f"{prefix}_mean_diff"] = np.mean(np.diff(mag))
    
    return feats

In [19]:
def extract_all_features(window):
    
    features = {}
    
    sensores = ["chest", "ankle", "arm"]
    
    for s in sensores:
        x = window[f"{s}_acc_x"].values
        y = window[f"{s}_acc_y"].values
        z = window[f"{s}_acc_z"].values
        
        feats = extract_sensor_features(x, y, z, s)
        features.update(feats)
    
    return features

In [20]:
def extract_dataset_features(df):
    
    features_list = []
    
    for i in range(0, len(df), window_size):
        window = df.iloc[i:i+window_size]
        
        if len(window) == window_size:
            
            feats = extract_all_features(window)
            feats["activity"] = window["activity_label"].iloc[0]
            
            features_list.append(feats)
    
    return pd.DataFrame(features_list)

In [21]:
df_features = extract_dataset_features(MHEALTHDATASET)

print(df_features.shape)
print(df_features.head())

(8104, 49)
   chest_mean_x  chest_mean_y  chest_mean_z  chest_std_x  chest_std_y  \
0     -9.729534      0.264533      0.712791     0.126265     0.141677
1     -9.731481      0.550312      0.779281     0.119918     0.252231
2     -9.715155      0.761215      0.755877     0.139140     0.127399
3     -9.750353      0.638619      0.865897     0.140315     0.224548
4     -9.730774      0.434492      1.028790     0.186802     0.196430

   chest_std_z  chest_max_x  chest_max_y  chest_max_z  chest_corr_xy  \
0     0.311775      -9.4273      0.62167       1.3564      -0.171394
1     0.231659      -9.3497      1.10650       1.2457      -0.032070
2     0.162377      -9.3402      1.17420       1.2298      -0.071088
3     0.160977      -9.3237      1.17220       1.2974      -0.065750
4     0.200479      -9.2637      1.12020       1.7127      -0.009411

   chest_corr_xz  chest_corr_yz  chest_mean_mag  chest_std_mag    chest_auc  \
0       0.142883       0.105413        9.765208       0.125756  1464.781178
1       0.020993      -0.570424        9.784117       0.120627  1467.617618
2      -0.122487       0.038881        9.776346       0.141564  1466.451934
3      -0.056857      -0.059844        9.813397       0.142308  1472.009559
4      -0.042883      -0.009827        9.798653       0.187701  1469.797901

   chest_mean_diff  ankle_mean_x  ankle_mean_y  ankle_mean_z  ankle_std_x  \
0         0.000731      1.805444     -9.651585      0.273809     0.243750
1        -0.000498      1.687448     -9.627662      0.402506     0.144514
2        -0.001455      1.602998     -9.624559      0.586885     0.098475
3        -0.000434      1.595748     -9.632805      0.567929     0.110065
4        -0.000983      1.938933     -9.625221      0.567434     0.927555

   ankle_std_y  ankle_std_z  ankle_max_x  ankle_max_y  ankle_max_z  \
0     0.109224     0.255348       2.4173      -9.3831      0.71098
1     0.113403     0.259734       2.1536      -9.3206      0.81747
2     0.102822     0.145349       1.9312      -9.2994      0.91528
3     0.102577     0.101671       1.8676      -9.3197      0.86912
4     0.445204     0.586248       4.9940      -8.1436      3.46100

   ankle_corr_xy  ankle_corr_xz  ankle_corr_yz  ankle_mean_mag  ankle_std_mag  \
0       0.268853       0.744293       0.337904        9.829212       0.104001
1      -0.026013       0.006822       0.188636        9.787223       0.113345
2      -0.161667       0.103369       0.181838        9.776335       0.104123
3      -0.106354       0.217191       0.119753        9.781716       0.104418
4       0.368296       0.238253       0.182635        9.893826       0.490693

     ankle_auc  ankle_mean_diff  arm_mean_x  arm_mean_y  arm_mean_z  \
0  1474.381858        -0.000614   -8.946337   -3.860197    0.160115
1  1468.083391        -0.000841   -8.980182   -3.823745   -0.188201
2  1466.450306         0.001759   -8.948965   -3.862915   -0.378146
3  1467.257365         0.000302   -8.258892   -4.688667    0.199317
4  1484.073861        -0.002409   -3.386609   -9.047753    1.338445

   arm_std_x  arm_std_y  arm_std_z  arm_max_x  arm_max_y  arm_max_z  \
0   0.181636   0.257151   0.129123    -8.4804    -3.3065   0.519680
1   0.153566   0.241659   0.276803    -8.5976    -3.2698   0.426380
2   0.119465   0.117152   0.113611    -8.6341    -3.4519  -0.043689
3   1.677488   1.854846   1.173320    -2.5555    -3.4418   5.695200
4   0.325091   0.252488   0.400945    -1.8955    -8.3119   3.204400

   arm_corr_xy  arm_corr_xz  arm_corr_yz  arm_mean_mag  arm_std_mag  \
0    -0.637107     0.015562     0.081825      9.750039     0.127377
1    -0.376037    -0.320223     0.684085      9.769338     0.136974
2    -0.251873    -0.031861     0.313754      9.755935     0.108278
3    -0.871007     0.778531    -0.721696      9.869766     0.671898
4    -0.075480     0.459808     0.144397      9.767054     0.239220

       arm_auc  arm_mean_diff  activity
0  1462.505852      -0.000521         0
1  1465.400633       0.000550         0
2  1463.390265       0.001081         0
3  1480.464892       0.001685         0
4  1465.058166       0.000487         0

<h1>Escalamiento</h1>

In [ ]:
from sklearn.preprocessing import StandardScaler

# Separar variables
X = MHEALTHDATASET.drop(columns=["activity_label", "subject_id"])
y = MHEALTHDATASET["activity_label"]
subject_ids = MHEALTHDATASET["subject_id"]

# Crear scaler
scaler = StandardScaler()

# Ajustar y transformar
X_scaled = scaler.fit_transform(X)

# Convertir nuevamente a DataFrame
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

# Volver a unir todo
MHEALTHDATASET_scaled = pd.concat(
    [X_scaled, y.reset_index(drop=True), subject_ids.reset_index(drop=True)],
    axis=1
)

MHEALTHDATASET_scaled.head()